#Makefile generated by Fortran Builder 5.3.1
#The following macros are machine specific
fblib = '../../../../../Program Files (x86)/NAG/FBuilder 5.3.1/lib'
NI_NAGFOR_Compiler = nagfor
NI_NAGFOR_CompOpts = -ideclient -abi=64 -g -O4 -double
NI_NAGFOR_NAGFORInfo = -gfb
NI_NAGFOR_CompOnly = -c
NI_NAGFOR_IFLAGS = 
NI_C_Compiler = nagfor =C
NI_C_CompOpts = -ideclient -abi=64 -g -O4 -Wc,-Wall
NI_C_CompOnly = -c
NI_IFLAGS = 
NI_CPP_Compiler = nagfor
NI_ALLOPTS = 
NI_Link = nagfor
NI_LibPath = -L'../../../../../Program Files (x86)/NAG/FBuilder 5.3.1/lib64' -L$(fblib) 
NI_LDFLAGS = 
NI_RM = fbrm 

#File extensions used in this Makefile
.SUFFIXES:
.SUFFIXES: .f90 .o 

#Output file
NI_OUTPUT = main.exe

#Target name
NI_TARGET = main.exe

#Object files
NI_OBJS =	 \
	main.o

#Depend Object files
NI_DOBJS =	 \
	main.o

#Prospective Module files
NI_MODS =	
#Fortran Information files
NI_FIFS =	 \
	main.fif

#Library files
NI_LIBS = 

#Dependencies
NI_EQ==
NI_SC=\;
main.o:	main.f90

#Default make target rule
$(NI_TARGET):$(NI_OBJS)
	@echo @link
	$(NI_Link) -o $(NI_OUTPUT) $(NI_LibPath) $(NI_DOBJS) $(NI_LDFLAGS) $(NI_NAGFOR_CompOpts) $(NI_LIBS)

#Other rules
main.o:
	@echo @nagfor main.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) main.fif -c main.f90

#Rebuild rule
all:clean $(NI_OBJS)
	@echo @link
	$(NI_Link) -o $(NI_OUTPUT) $(NI_LibPath) $(NI_DOBJS) $(NI_LDFLAGS) $(NI_NAGFOR_CompOpts) $(NI_LIBS)

#Clean rule
clean:
	$(NI_RM) $(NI_OUTPUT) $(NI_DOBJS) $(NI_MODS) $(NI_FIFS) fbvalwatch.vwi
